user  root;
worker_processes  5;

events {
}

http {
    include /etc/nginx/mime.types;

    types {
        application/javascript    js mjs;
        text/javascript          js mjs;
        text/css                 css;
        image/svg+xml           svg svgz;
    }

    server {
		listen		 443 ssl;
        server_name  mihest.ru www.mihest.ru;

        location /api {
            proxy_pass http://accounts:8081;
            proxy_set_header Host $host;
        }
        
        location /media {
            proxy_pass http://accounts:8081;
            proxy_set_header Host $host;
        }

        location = /index.html {
            return 301 /;
        }

        location ~ ^/(.+)\.html$ {
            return 301 /$1$is_args$args;
        }

        location / {
            root /frontend;
            try_files $uri $uri/ $uri.html /index.html;
        }

        ssl_certificate /etc/nginx/ssl/mihest.crt;
		ssl_certificate_key /etc/nginx/ssl/mihest.key;

    }
    server {
		listen       80;
		return         301 https://$server_name$request_uri;
	}
}