"""add_quests_table

Revision ID: 3ffc3472e115
Revises: 2683ed3b0711
Create Date: 2026-04-27 15:08:41.695525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '3ffc3472e115'
down_revision: Union[str, Sequence[str], None] = '2683ed3b0711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'quests',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('author_id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=120), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('city_district', sa.String(length=120), nullable=False),
        sa.Column('cover_file', sa.String(), nullable=True),
        sa.Column('difficulty', sa.SmallInteger(), nullable=False),
        sa.Column('duration_minutes', sa.Integer(), nullable=False),
        sa.Column('rules_warning', sa.Text(), nullable=True),
        sa.Column('status', sa.Enum('DRAFT', 'MODERATION', 'PUBLISHED', 'ARCHIVE', 'HIDDEN', name='queststatusenum'),
                  nullable=False),
        sa.Column('rejection_reason', sa.Text(), nullable=True),
        sa.Column('start_lat', sa.Float(), nullable=True),
        sa.Column('start_lng', sa.Float(), nullable=True),
        sa.Column('start_point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2,
                                                             from_text='ST_GeogFromText', name='geography'),
                  nullable=True),
        sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint('char_length(description) >= 30', name='check_quest_description_min_len'),
        sa.CheckConstraint('char_length(title) >= 5', name='check_quest_title_min_len'),
        sa.CheckConstraint('difficulty >= 1 AND difficulty <= 5', name='check_quest_difficulty_range'),
        sa.CheckConstraint('duration_minutes > 0', name='check_quest_duration_positive'),
        sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quests_start_point', 'quests', ['start_point'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index('ix_quests_author_id', 'quests', ['author_id'], unique=False, if_not_exists=True)
    op.create_index('ix_quests_city_district', 'quests', ['city_district'], unique=False, if_not_exists=True)
    op.create_index('ix_quests_created_at', 'quests', ['created_at'], unique=False, if_not_exists=True)
    op.create_index('ix_quests_difficulty', 'quests', ['difficulty'], unique=False, if_not_exists=True)
    op.create_index('ix_quests_duration_minutes', 'quests', ['duration_minutes'], unique=False, if_not_exists=True)
    op.create_index('ix_quests_start_point', 'quests', ['start_point'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_index('ix_quests_status', 'quests', ['status'], unique=False, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quests_status', table_name='quests')
    op.drop_index('ix_quests_start_point', table_name='quests', postgresql_using='gist')
    op.drop_index('ix_quests_duration_minutes', table_name='quests')
    op.drop_index('ix_quests_difficulty', table_name='quests')
    op.drop_index('ix_quests_created_at', table_name='quests')
    op.drop_index('ix_quests_city_district', table_name='quests')
    op.drop_index('ix_quests_author_id', table_name='quests')
    op.drop_index('idx_quests_start_point', table_name='quests', postgresql_using='gist')
    op.drop_table('quests')
    # ### end Alembic commands ###
