"""edit team_members table

Revision ID: d1f066ad0642
Revises: 3ffc3472e115
Create Date: 2026-04-28 13:13:54.473554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f066ad0642'
down_revision: Union[str, Sequence[str], None] = '3ffc3472e115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_team'), 'team_members', type_='unique')
    op.create_unique_constraint('uq_user_team', 'team_members', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_team', 'team_members', type_='unique')
    op.create_unique_constraint(op.f('uq_user_team'), 'team_members', ['user_id', 'team_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
